# Generated by Django 5.2.1 on 2025-05-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chapterimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chapterimage',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='chapterimage',
            unique_together={('chapter', 'order')},
        ),
    ]
