# Generated by Django 5.2.1 on 2025-05-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chapterimage_options_chapterimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapterimage',
            unique_together=set(),
        ),
    ]
