# Generated by Django 5.2.1 on 2025-05-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_chapterimage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'book')},
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.book'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='chapter',
        ),
    ]
