# Generated by Django 5.2.1 on 2025-06-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_notification_user_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'читатель'), ('writer', 'писатель'), ('admin', 'админ')], default='reader', max_length=10),
        ),
    ]
